

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SampleProject
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbFilesEntities : DbContext
{
    public dbFilesEntities()
        : base("name=dbFilesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<File> Files { get; set; }

    public virtual DbSet<videoview> videoviews { get; set; }

}

}

